[build]
  command = "npm run build"
  publish = "dist"
  
[dev]
  command = "npm run dev"
  targetPort = 5173 # Vite's default port
  
[build.environment]
  NODE_VERSION = "18.19.0" # Matching .nvmrc
  NPM_VERSION = "10.2.4"   # Latest stable NPM version compatible with Node 18

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Handle SPA routing
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 