// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://***REMOVED***.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsaXV5aG9wZWx1cHlrcWdkZWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODA0ODUsImV4cCI6MjA1NjQ1NjQ4NX0.aaV7c-tfQPdt_NbW1huw4g7IJOTescGN0TZHXwWfMU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);